defaults:
  - callbacks/callbacks

device: ${device}

_target_: 

output_dir: models
save_last: True # Save the last checkpoint
eval_at_end: test # False or which loader (e.g. val, test) to evaluate at the end of training

epochs: 30
