_target_: src.trainer.callbacks.checkpoint.checkpoint.Checkpoint
output_dir: checkpoints

every_n_epochs: 5                       # Save checkpoint every n epochs
last: True                              # Save the last checkpoint
best: True                              # Save the best checkpoint