name: Validate

on:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/validate.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pylint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pylint
        run: pip install pylint==3.3.1
      - name: Run pylint
        run: pylint src
  pytest:
    name: PyTesting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pytest 
        run: PYTHONPATH=${CWD}:$PYTHONPATH pytest src
